//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_VMISOCreate_OSService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:scg.co.th:PAPER:VMI:SO", ConfigurationName="SI_VMISOCreate_OSService.SI_VMISOCreate_OS")]
    public interface SI_VMISOCreate_OS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SI_VMISOCreate_OSService.SI_VMISOCreate_OSResponse> SI_VMISOCreate_OSAsync(SI_VMISOCreate_OSService.SI_VMISOCreate_OSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISOCreateReq
    {
        
        private string rEFERENCE_IDField;
        
        private string tESTRUNField;
        
        private DT_VMISOCreateReqItem[] sALES_HEADER_INField;
        
        private DT_VMISOCreateReqItem1[] sALES_ITEMS_INField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string REFERENCE_ID
        {
            get
            {
                return this.rEFERENCE_IDField;
            }
            set
            {
                this.rEFERENCE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TESTRUN
        {
            get
            {
                return this.tESTRUNField;
            }
            set
            {
                this.tESTRUNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISOCreateReqItem[] SALES_HEADER_IN
        {
            get
            {
                return this.sALES_HEADER_INField;
            }
            set
            {
                this.sALES_HEADER_INField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISOCreateReqItem1[] SALES_ITEMS_IN
        {
            get
            {
                return this.sALES_ITEMS_INField;
            }
            set
            {
                this.sALES_ITEMS_INField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISOCreateReqItem
    {
        
        private string wEB_ORDER_IDField;
        
        private string dOC_TYPEField;
        
        private string sALES_ORGField;
        
        private string dISTR_CHANField;
        
        private string dIVISIONField;
        
        private string pO_METHODField;
        
        private string pURCH_NO_CField;
        
        private System.DateTime rEQ_DATE_HField;
        
        private bool rEQ_DATE_HFieldSpecified;
        
        private string cURRENCYField;
        
        private string sOLD_TOField;
        
        private string sHIP_TOField;
        
        private string bILL_TOField;
        
        private string uNLOAD_PTField;
        
        private System.DateTime pURCH_DATEField;
        
        private bool pURCH_DATEFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WEB_ORDER_ID
        {
            get
            {
                return this.wEB_ORDER_IDField;
            }
            set
            {
                this.wEB_ORDER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DOC_TYPE
        {
            get
            {
                return this.dOC_TYPEField;
            }
            set
            {
                this.dOC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SALES_ORG
        {
            get
            {
                return this.sALES_ORGField;
            }
            set
            {
                this.sALES_ORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DISTR_CHAN
        {
            get
            {
                return this.dISTR_CHANField;
            }
            set
            {
                this.dISTR_CHANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DIVISION
        {
            get
            {
                return this.dIVISIONField;
            }
            set
            {
                this.dIVISIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PO_METHOD
        {
            get
            {
                return this.pO_METHODField;
            }
            set
            {
                this.pO_METHODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PURCH_NO_C
        {
            get
            {
                return this.pURCH_NO_CField;
            }
            set
            {
                this.pURCH_NO_CField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime REQ_DATE_H
        {
            get
            {
                return this.rEQ_DATE_HField;
            }
            set
            {
                this.rEQ_DATE_HField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REQ_DATE_HSpecified
        {
            get
            {
                return this.rEQ_DATE_HFieldSpecified;
            }
            set
            {
                this.rEQ_DATE_HFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SOLD_TO
        {
            get
            {
                return this.sOLD_TOField;
            }
            set
            {
                this.sOLD_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string SHIP_TO
        {
            get
            {
                return this.sHIP_TOField;
            }
            set
            {
                this.sHIP_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string BILL_TO
        {
            get
            {
                return this.bILL_TOField;
            }
            set
            {
                this.bILL_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string UNLOAD_PT
        {
            get
            {
                return this.uNLOAD_PTField;
            }
            set
            {
                this.uNLOAD_PTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public System.DateTime PURCH_DATE
        {
            get
            {
                return this.pURCH_DATEField;
            }
            set
            {
                this.pURCH_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PURCH_DATESpecified
        {
            get
            {
                return this.pURCH_DATEFieldSpecified;
            }
            set
            {
                this.pURCH_DATEFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISOCreateRes
    {
        
        private string rEFERENCE_IDField;
        
        private DT_VMISOCreateResItem[] rETURNField;
        
        private DT_VMISOCreateResItem1[] sALES_HEADER_OUTField;
        
        private DT_VMISOCreateResItem2[] sALES_ITEMS_OUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string REFERENCE_ID
        {
            get
            {
                return this.rEFERENCE_IDField;
            }
            set
            {
                this.rEFERENCE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISOCreateResItem[] RETURN
        {
            get
            {
                return this.rETURNField;
            }
            set
            {
                this.rETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISOCreateResItem1[] SALES_HEADER_OUT
        {
            get
            {
                return this.sALES_HEADER_OUTField;
            }
            set
            {
                this.sALES_HEADER_OUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISOCreateResItem2[] SALES_ITEMS_OUT
        {
            get
            {
                return this.sALES_ITEMS_OUTField;
            }
            set
            {
                this.sALES_ITEMS_OUTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISOCreateResItem
    {
        
        private string wEB_ORDER_IDField;
        
        private string iTM_NUMBERField;
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WEB_ORDER_ID
        {
            get
            {
                return this.wEB_ORDER_IDField;
            }
            set
            {
                this.wEB_ORDER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ITM_NUMBER
        {
            get
            {
                return this.iTM_NUMBERField;
            }
            set
            {
                this.iTM_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NUMBER
        {
            get
            {
                return this.nUMBERField;
            }
            set
            {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISOCreateResItem1
    {
        
        private string wEB_ORDER_IDField;
        
        private string dOC_NUMBERField;
        
        private string cURRENCYField;
        
        private decimal nET_VAL_HDField;
        
        private bool nET_VAL_HDFieldSpecified;
        
        private decimal tAX_AMOUNTField;
        
        private bool tAX_AMOUNTFieldSpecified;
        
        private string sOLD_TOField;
        
        private string sHIP_TOField;
        
        private string bILL_TOField;
        
        private string uNLOAD_PTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WEB_ORDER_ID
        {
            get
            {
                return this.wEB_ORDER_IDField;
            }
            set
            {
                this.wEB_ORDER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DOC_NUMBER
        {
            get
            {
                return this.dOC_NUMBERField;
            }
            set
            {
                this.dOC_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal NET_VAL_HD
        {
            get
            {
                return this.nET_VAL_HDField;
            }
            set
            {
                this.nET_VAL_HDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NET_VAL_HDSpecified
        {
            get
            {
                return this.nET_VAL_HDFieldSpecified;
            }
            set
            {
                this.nET_VAL_HDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal TAX_AMOUNT
        {
            get
            {
                return this.tAX_AMOUNTField;
            }
            set
            {
                this.tAX_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TAX_AMOUNTSpecified
        {
            get
            {
                return this.tAX_AMOUNTFieldSpecified;
            }
            set
            {
                this.tAX_AMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SOLD_TO
        {
            get
            {
                return this.sOLD_TOField;
            }
            set
            {
                this.sOLD_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SHIP_TO
        {
            get
            {
                return this.sHIP_TOField;
            }
            set
            {
                this.sHIP_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string BILL_TO
        {
            get
            {
                return this.bILL_TOField;
            }
            set
            {
                this.bILL_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string UNLOAD_PT
        {
            get
            {
                return this.uNLOAD_PTField;
            }
            set
            {
                this.uNLOAD_PTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISOCreateResItem2
    {
        
        private string wEB_ORDER_IDField;
        
        private string dOC_NUMBERField;
        
        private string iTM_NUMBERField;
        
        private string mATERIALField;
        
        private string cUST_MAT35Field;
        
        private string sHORT_TEXTField;
        
        private string pLANTField;
        
        private string bATCHField;
        
        private string sALES_UNITField;
        
        private string vMI_MATTYPEField;
        
        private string vMI_RRNOField;
        
        private string hG_LV_ITEMField;
        
        private decimal uNIT_PRICEField;
        
        private bool uNIT_PRICEFieldSpecified;
        
        private decimal nET_VALUEField;
        
        private bool nET_VALUEFieldSpecified;
        
        private decimal tAX_AMOUNTField;
        
        private bool tAX_AMOUNTFieldSpecified;
        
        private System.DateTime rEQ_DATEField;
        
        private bool rEQ_DATEFieldSpecified;
        
        private decimal rEQ_QTYField;
        
        private bool rEQ_QTYFieldSpecified;
        
        private decimal cUM_CF_QTYField;
        
        private bool cUM_CF_QTYFieldSpecified;
        
        private string iTEM_NOTEField;
        
        private System.DateTime pO_DAT_SField;
        
        private bool pO_DAT_SFieldSpecified;
        
        private string pOITM_NO_SField;
        
        private string iTEM_CATEGField;
        
        private string dUE_PROMISE_TIMEField;
        
        private string pROD_PLANNING_STATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WEB_ORDER_ID
        {
            get
            {
                return this.wEB_ORDER_IDField;
            }
            set
            {
                this.wEB_ORDER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DOC_NUMBER
        {
            get
            {
                return this.dOC_NUMBERField;
            }
            set
            {
                this.dOC_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ITM_NUMBER
        {
            get
            {
                return this.iTM_NUMBERField;
            }
            set
            {
                this.iTM_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MATERIAL
        {
            get
            {
                return this.mATERIALField;
            }
            set
            {
                this.mATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CUST_MAT35
        {
            get
            {
                return this.cUST_MAT35Field;
            }
            set
            {
                this.cUST_MAT35Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SHORT_TEXT
        {
            get
            {
                return this.sHORT_TEXTField;
            }
            set
            {
                this.sHORT_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PLANT
        {
            get
            {
                return this.pLANTField;
            }
            set
            {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string BATCH
        {
            get
            {
                return this.bATCHField;
            }
            set
            {
                this.bATCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SALES_UNIT
        {
            get
            {
                return this.sALES_UNITField;
            }
            set
            {
                this.sALES_UNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string VMI_MATTYPE
        {
            get
            {
                return this.vMI_MATTYPEField;
            }
            set
            {
                this.vMI_MATTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string VMI_RRNO
        {
            get
            {
                return this.vMI_RRNOField;
            }
            set
            {
                this.vMI_RRNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string HG_LV_ITEM
        {
            get
            {
                return this.hG_LV_ITEMField;
            }
            set
            {
                this.hG_LV_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal UNIT_PRICE
        {
            get
            {
                return this.uNIT_PRICEField;
            }
            set
            {
                this.uNIT_PRICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UNIT_PRICESpecified
        {
            get
            {
                return this.uNIT_PRICEFieldSpecified;
            }
            set
            {
                this.uNIT_PRICEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal NET_VALUE
        {
            get
            {
                return this.nET_VALUEField;
            }
            set
            {
                this.nET_VALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NET_VALUESpecified
        {
            get
            {
                return this.nET_VALUEFieldSpecified;
            }
            set
            {
                this.nET_VALUEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal TAX_AMOUNT
        {
            get
            {
                return this.tAX_AMOUNTField;
            }
            set
            {
                this.tAX_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TAX_AMOUNTSpecified
        {
            get
            {
                return this.tAX_AMOUNTFieldSpecified;
            }
            set
            {
                this.tAX_AMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public System.DateTime REQ_DATE
        {
            get
            {
                return this.rEQ_DATEField;
            }
            set
            {
                this.rEQ_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REQ_DATESpecified
        {
            get
            {
                return this.rEQ_DATEFieldSpecified;
            }
            set
            {
                this.rEQ_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal REQ_QTY
        {
            get
            {
                return this.rEQ_QTYField;
            }
            set
            {
                this.rEQ_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REQ_QTYSpecified
        {
            get
            {
                return this.rEQ_QTYFieldSpecified;
            }
            set
            {
                this.rEQ_QTYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public decimal CUM_CF_QTY
        {
            get
            {
                return this.cUM_CF_QTYField;
            }
            set
            {
                this.cUM_CF_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CUM_CF_QTYSpecified
        {
            get
            {
                return this.cUM_CF_QTYFieldSpecified;
            }
            set
            {
                this.cUM_CF_QTYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string ITEM_NOTE
        {
            get
            {
                return this.iTEM_NOTEField;
            }
            set
            {
                this.iTEM_NOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public System.DateTime PO_DAT_S
        {
            get
            {
                return this.pO_DAT_SField;
            }
            set
            {
                this.pO_DAT_SField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PO_DAT_SSpecified
        {
            get
            {
                return this.pO_DAT_SFieldSpecified;
            }
            set
            {
                this.pO_DAT_SFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string POITM_NO_S
        {
            get
            {
                return this.pOITM_NO_SField;
            }
            set
            {
                this.pOITM_NO_SField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string ITEM_CATEG
        {
            get
            {
                return this.iTEM_CATEGField;
            }
            set
            {
                this.iTEM_CATEGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string DUE_PROMISE_TIME
        {
            get
            {
                return this.dUE_PROMISE_TIMEField;
            }
            set
            {
                this.dUE_PROMISE_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string PROD_PLANNING_STATUS
        {
            get
            {
                return this.pROD_PLANNING_STATUSField;
            }
            set
            {
                this.pROD_PLANNING_STATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISOCreateReqItem1
    {
        
        private string wEB_ORDER_IDField;
        
        private string iTM_NUMBERField;
        
        private string mATERIALField;
        
        private string cUST_MAT35Field;
        
        private string pLANTField;
        
        private string bATCHField;
        
        private string sALES_UNITField;
        
        private string vMI_RRNOField;
        
        private System.DateTime rEQ_DATEField;
        
        private bool rEQ_DATEFieldSpecified;
        
        private decimal rEQ_QTYField;
        
        private bool rEQ_QTYFieldSpecified;
        
        private string iTEM_NOTEField;
        
        private System.DateTime pO_DAT_SField;
        
        private bool pO_DAT_SFieldSpecified;
        
        private string pOITM_NO_SField;
        
        private string iTEM_CATEGField;
        
        private string dUE_PROMISE_TIMEField;
        
        private string pROD_PLANNING_STATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WEB_ORDER_ID
        {
            get
            {
                return this.wEB_ORDER_IDField;
            }
            set
            {
                this.wEB_ORDER_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ITM_NUMBER
        {
            get
            {
                return this.iTM_NUMBERField;
            }
            set
            {
                this.iTM_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MATERIAL
        {
            get
            {
                return this.mATERIALField;
            }
            set
            {
                this.mATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CUST_MAT35
        {
            get
            {
                return this.cUST_MAT35Field;
            }
            set
            {
                this.cUST_MAT35Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PLANT
        {
            get
            {
                return this.pLANTField;
            }
            set
            {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string BATCH
        {
            get
            {
                return this.bATCHField;
            }
            set
            {
                this.bATCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SALES_UNIT
        {
            get
            {
                return this.sALES_UNITField;
            }
            set
            {
                this.sALES_UNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string VMI_RRNO
        {
            get
            {
                return this.vMI_RRNOField;
            }
            set
            {
                this.vMI_RRNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime REQ_DATE
        {
            get
            {
                return this.rEQ_DATEField;
            }
            set
            {
                this.rEQ_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REQ_DATESpecified
        {
            get
            {
                return this.rEQ_DATEFieldSpecified;
            }
            set
            {
                this.rEQ_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal REQ_QTY
        {
            get
            {
                return this.rEQ_QTYField;
            }
            set
            {
                this.rEQ_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REQ_QTYSpecified
        {
            get
            {
                return this.rEQ_QTYFieldSpecified;
            }
            set
            {
                this.rEQ_QTYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ITEM_NOTE
        {
            get
            {
                return this.iTEM_NOTEField;
            }
            set
            {
                this.iTEM_NOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public System.DateTime PO_DAT_S
        {
            get
            {
                return this.pO_DAT_SField;
            }
            set
            {
                this.pO_DAT_SField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PO_DAT_SSpecified
        {
            get
            {
                return this.pO_DAT_SFieldSpecified;
            }
            set
            {
                this.pO_DAT_SFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string POITM_NO_S
        {
            get
            {
                return this.pOITM_NO_SField;
            }
            set
            {
                this.pOITM_NO_SField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ITEM_CATEG
        {
            get
            {
                return this.iTEM_CATEGField;
            }
            set
            {
                this.iTEM_CATEGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string DUE_PROMISE_TIME
        {
            get
            {
                return this.dUE_PROMISE_TIMEField;
            }
            set
            {
                this.dUE_PROMISE_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string PROD_PLANNING_STATUS
        {
            get
            {
                return this.pROD_PLANNING_STATUSField;
            }
            set
            {
                this.pROD_PLANNING_STATUSField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_VMISOCreate_OSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:scg.co.th:PAPER:VMI:SO", Order=0)]
        public SI_VMISOCreate_OSService.DT_VMISOCreateReq MT_VMISOCreateReq;
        
        public SI_VMISOCreate_OSRequest()
        {
        }
        
        public SI_VMISOCreate_OSRequest(SI_VMISOCreate_OSService.DT_VMISOCreateReq MT_VMISOCreateReq)
        {
            this.MT_VMISOCreateReq = MT_VMISOCreateReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_VMISOCreate_OSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:scg.co.th:PAPER:VMI:SO", Order=0)]
        public SI_VMISOCreate_OSService.DT_VMISOCreateRes MT_VMISOCreateRes;
        
        public SI_VMISOCreate_OSResponse()
        {
        }
        
        public SI_VMISOCreate_OSResponse(SI_VMISOCreate_OSService.DT_VMISOCreateRes MT_VMISOCreateRes)
        {
            this.MT_VMISOCreateRes = MT_VMISOCreateRes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface SI_VMISOCreate_OSChannel : SI_VMISOCreate_OSService.SI_VMISOCreate_OS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class SI_VMISOCreate_OSClient : System.ServiceModel.ClientBase<SI_VMISOCreate_OSService.SI_VMISOCreate_OS>, SI_VMISOCreate_OSService.SI_VMISOCreate_OS
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SI_VMISOCreate_OSClient(EndpointConfiguration endpointConfiguration) : 
                base(SI_VMISOCreate_OSClient.GetBindingForEndpoint(endpointConfiguration), SI_VMISOCreate_OSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_VMISOCreate_OSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SI_VMISOCreate_OSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_VMISOCreate_OSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SI_VMISOCreate_OSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_VMISOCreate_OSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SI_VMISOCreate_OSService.SI_VMISOCreate_OSResponse> SI_VMISOCreate_OSService.SI_VMISOCreate_OS.SI_VMISOCreate_OSAsync(SI_VMISOCreate_OSService.SI_VMISOCreate_OSRequest request)
        {
            return base.Channel.SI_VMISOCreate_OSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SI_VMISOCreate_OSService.SI_VMISOCreate_OSResponse> SI_VMISOCreate_OSAsync(SI_VMISOCreate_OSService.DT_VMISOCreateReq MT_VMISOCreateReq)
        {
            SI_VMISOCreate_OSService.SI_VMISOCreate_OSRequest inValue = new SI_VMISOCreate_OSService.SI_VMISOCreate_OSRequest();
            inValue.MT_VMISOCreateReq = MT_VMISOCreateReq;
            return ((SI_VMISOCreate_OSService.SI_VMISOCreate_OS)(this)).SI_VMISOCreate_OSAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public new virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port_D))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port_Q))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port_P))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port_D))
            {
                return new System.ServiceModel.EndpointAddress("https://cxdwd.scg.co.th/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
                        "S_PAPER_VMI_D&receiverParty=&receiverService=&interface=SI_VMISOCreate_OS&interf" +
                        "aceNamespace=urn%3Ascg.co.th%3APAPER%3AVMI%3ASO");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port_Q))
            {
                return new System.ServiceModel.EndpointAddress("https://cxqwd.scg.co.th/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
                        "S_PAPER_VMI_Q&receiverParty=&receiverService=&interface=SI_VMISOCreate_OS&interf" +
                        "aceNamespace=urn%3Ascg.co.th%3APAPER%3AVMI%3ASO");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port_P))
            {
                return new System.ServiceModel.EndpointAddress("https://cxpwd.scg.co.th/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
                        "S_PAPER_VMI_P&receiverParty=&receiverService=&interface=SI_VMISOCreate_OS&interf" +
                        "aceNamespace=urn%3Ascg.co.th%3APAPER%3AVMI%3ASO");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port_D,
            
            HTTPS_Port_Q,
            
            HTTPS_Port_P,
        }
    }
}
