//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_VMISODetailInquiry_OSService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:scg.co.th:PAPER:VMI:SO", ConfigurationName="SI_VMISODetailInquiry_OSService.SI_VMISODetailInquiry_OS")]
    public interface SI_VMISODetailInquiry_OS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SI_VMISODetailInquiry_OSService.SI_VMISODetailInquiry_OSResponse> SI_VMISODetailInquiry_OSAsync(SI_VMISODetailInquiry_OSService.SI_VMISODetailInquiry_OSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISODetailInquiryReq
    {
        
        private System.DateTime rEC_DATEField;
        
        private System.DateTime rEC_DATE_TOField;
        
        private DT_VMISODetailInquiryReqItem[] cUSTOMER_INField;
        
        private DT_VMISODetailInquiryReqItem1[] dOC_NUMBER_INField;
        
        private DT_VMISODetailInquiryReqItem2[] mATERIAL_INField;
        
        private DT_VMISODetailInquiryReqItem3[] oRGANIZATION_INField;
        
        private DT_VMISODetailInquiryReqItem4[] pLANT_INField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime REC_DATE
        {
            get
            {
                return this.rEC_DATEField;
            }
            set
            {
                this.rEC_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime REC_DATE_TO
        {
            get
            {
                return this.rEC_DATE_TOField;
            }
            set
            {
                this.rEC_DATE_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISODetailInquiryReqItem[] CUSTOMER_IN
        {
            get
            {
                return this.cUSTOMER_INField;
            }
            set
            {
                this.cUSTOMER_INField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISODetailInquiryReqItem1[] DOC_NUMBER_IN
        {
            get
            {
                return this.dOC_NUMBER_INField;
            }
            set
            {
                this.dOC_NUMBER_INField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISODetailInquiryReqItem2[] MATERIAL_IN
        {
            get
            {
                return this.mATERIAL_INField;
            }
            set
            {
                this.mATERIAL_INField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISODetailInquiryReqItem3[] ORGANIZATION_IN
        {
            get
            {
                return this.oRGANIZATION_INField;
            }
            set
            {
                this.oRGANIZATION_INField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISODetailInquiryReqItem4[] PLANT_IN
        {
            get
            {
                return this.pLANT_INField;
            }
            set
            {
                this.pLANT_INField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISODetailInquiryReqItem
    {
        
        private string sOLD_TOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SOLD_TO
        {
            get
            {
                return this.sOLD_TOField;
            }
            set
            {
                this.sOLD_TOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISODetailInquiryRes
    {
        
        private DT_VMISODetailInquiryResItem[] dELIVERY_OUTField;
        
        private DT_VMISODetailInquiryResItem1[] rETURNField;
        
        private DT_VMISODetailInquiryResItem2[] sALES_HEADER_OUTField;
        
        private DT_VMISODetailInquiryResItem3[] sALES_ITEMS_OUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISODetailInquiryResItem[] DELIVERY_OUT
        {
            get
            {
                return this.dELIVERY_OUTField;
            }
            set
            {
                this.dELIVERY_OUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISODetailInquiryResItem1[] RETURN
        {
            get
            {
                return this.rETURNField;
            }
            set
            {
                this.rETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISODetailInquiryResItem2[] SALES_HEADER_OUT
        {
            get
            {
                return this.sALES_HEADER_OUTField;
            }
            set
            {
                this.sALES_HEADER_OUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VMISODetailInquiryResItem3[] SALES_ITEMS_OUT
        {
            get
            {
                return this.sALES_ITEMS_OUTField;
            }
            set
            {
                this.sALES_ITEMS_OUTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISODetailInquiryResItem
    {
        
        private string dOC_NUMBERField;
        
        private string iTM_NUMBERField;
        
        private string dELIVERYField;
        
        private string dELIVERY_ITEMField;
        
        private string mATERIALField;
        
        private string sALES_UNITField;
        
        private System.DateTime gI_DATEField;
        
        private bool gI_DATEFieldSpecified;
        
        private decimal dELIVERY_QTYField;
        
        private bool dELIVERY_QTYFieldSpecified;
        
        private string gI_STATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DOC_NUMBER
        {
            get
            {
                return this.dOC_NUMBERField;
            }
            set
            {
                this.dOC_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ITM_NUMBER
        {
            get
            {
                return this.iTM_NUMBERField;
            }
            set
            {
                this.iTM_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DELIVERY
        {
            get
            {
                return this.dELIVERYField;
            }
            set
            {
                this.dELIVERYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DELIVERY_ITEM
        {
            get
            {
                return this.dELIVERY_ITEMField;
            }
            set
            {
                this.dELIVERY_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MATERIAL
        {
            get
            {
                return this.mATERIALField;
            }
            set
            {
                this.mATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SALES_UNIT
        {
            get
            {
                return this.sALES_UNITField;
            }
            set
            {
                this.sALES_UNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime GI_DATE
        {
            get
            {
                return this.gI_DATEField;
            }
            set
            {
                this.gI_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GI_DATESpecified
        {
            get
            {
                return this.gI_DATEFieldSpecified;
            }
            set
            {
                this.gI_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal DELIVERY_QTY
        {
            get
            {
                return this.dELIVERY_QTYField;
            }
            set
            {
                this.dELIVERY_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DELIVERY_QTYSpecified
        {
            get
            {
                return this.dELIVERY_QTYFieldSpecified;
            }
            set
            {
                this.dELIVERY_QTYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string GI_STATUS
        {
            get
            {
                return this.gI_STATUSField;
            }
            set
            {
                this.gI_STATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISODetailInquiryResItem1
    {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER
        {
            get
            {
                return this.nUMBERField;
            }
            set
            {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISODetailInquiryResItem2
    {
        
        private string dOC_NUMBERField;
        
        private System.DateTime rEC_DATEField;
        
        private bool rEC_DATEFieldSpecified;
        
        private string dOC_TYPEField;
        
        private string sALES_ORGField;
        
        private string dISTR_CHANField;
        
        private string dIVISIONField;
        
        private string pO_METHODField;
        
        private string pURCH_NO_CField;
        
        private System.DateTime rEQ_DATE_HField;
        
        private bool rEQ_DATE_HFieldSpecified;
        
        private string cURRENCYField;
        
        private decimal nET_VAL_HDField;
        
        private bool nET_VAL_HDFieldSpecified;
        
        private decimal tAX_AMOUNTField;
        
        private bool tAX_AMOUNTFieldSpecified;
        
        private string sOLD_TOField;
        
        private string sHIP_TOField;
        
        private string bILL_TOField;
        
        private string uNLOAD_PTField;
        
        private System.DateTime pURCH_DATEField;
        
        private bool pURCH_DATEFieldSpecified;
        
        private string cREDIT_STATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DOC_NUMBER
        {
            get
            {
                return this.dOC_NUMBERField;
            }
            set
            {
                this.dOC_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime REC_DATE
        {
            get
            {
                return this.rEC_DATEField;
            }
            set
            {
                this.rEC_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_DATESpecified
        {
            get
            {
                return this.rEC_DATEFieldSpecified;
            }
            set
            {
                this.rEC_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DOC_TYPE
        {
            get
            {
                return this.dOC_TYPEField;
            }
            set
            {
                this.dOC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string SALES_ORG
        {
            get
            {
                return this.sALES_ORGField;
            }
            set
            {
                this.sALES_ORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DISTR_CHAN
        {
            get
            {
                return this.dISTR_CHANField;
            }
            set
            {
                this.dISTR_CHANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DIVISION
        {
            get
            {
                return this.dIVISIONField;
            }
            set
            {
                this.dIVISIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PO_METHOD
        {
            get
            {
                return this.pO_METHODField;
            }
            set
            {
                this.pO_METHODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PURCH_NO_C
        {
            get
            {
                return this.pURCH_NO_CField;
            }
            set
            {
                this.pURCH_NO_CField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime REQ_DATE_H
        {
            get
            {
                return this.rEQ_DATE_HField;
            }
            set
            {
                this.rEQ_DATE_HField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REQ_DATE_HSpecified
        {
            get
            {
                return this.rEQ_DATE_HFieldSpecified;
            }
            set
            {
                this.rEQ_DATE_HFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal NET_VAL_HD
        {
            get
            {
                return this.nET_VAL_HDField;
            }
            set
            {
                this.nET_VAL_HDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NET_VAL_HDSpecified
        {
            get
            {
                return this.nET_VAL_HDFieldSpecified;
            }
            set
            {
                this.nET_VAL_HDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal TAX_AMOUNT
        {
            get
            {
                return this.tAX_AMOUNTField;
            }
            set
            {
                this.tAX_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TAX_AMOUNTSpecified
        {
            get
            {
                return this.tAX_AMOUNTFieldSpecified;
            }
            set
            {
                this.tAX_AMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string SOLD_TO
        {
            get
            {
                return this.sOLD_TOField;
            }
            set
            {
                this.sOLD_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SHIP_TO
        {
            get
            {
                return this.sHIP_TOField;
            }
            set
            {
                this.sHIP_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string BILL_TO
        {
            get
            {
                return this.bILL_TOField;
            }
            set
            {
                this.bILL_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string UNLOAD_PT
        {
            get
            {
                return this.uNLOAD_PTField;
            }
            set
            {
                this.uNLOAD_PTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public System.DateTime PURCH_DATE
        {
            get
            {
                return this.pURCH_DATEField;
            }
            set
            {
                this.pURCH_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PURCH_DATESpecified
        {
            get
            {
                return this.pURCH_DATEFieldSpecified;
            }
            set
            {
                this.pURCH_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string CREDIT_STATUS
        {
            get
            {
                return this.cREDIT_STATUSField;
            }
            set
            {
                this.cREDIT_STATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISODetailInquiryResItem3
    {
        
        private string dOC_NUMBERField;
        
        private string iTM_NUMBERField;
        
        private string mATERIALField;
        
        private string cUST_MAT35Field;
        
        private string sHORT_TEXTField;
        
        private string pLANTField;
        
        private string bATCHField;
        
        private string sALES_UNITField;
        
        private string vMI_MATTYPEField;
        
        private string vMI_RRNOField;
        
        private string hG_LV_ITEMField;
        
        private decimal uNIT_PRICEField;
        
        private bool uNIT_PRICEFieldSpecified;
        
        private decimal nET_VALUEField;
        
        private bool nET_VALUEFieldSpecified;
        
        private decimal tAX_AMOUNTField;
        
        private bool tAX_AMOUNTFieldSpecified;
        
        private System.DateTime rEQ_DATEField;
        
        private bool rEQ_DATEFieldSpecified;
        
        private decimal rEQ_QTYField;
        
        private bool rEQ_QTYFieldSpecified;
        
        private decimal cUM_CF_QTYField;
        
        private bool cUM_CF_QTYFieldSpecified;
        
        private decimal dELIVERY_QTYField;
        
        private bool dELIVERY_QTYFieldSpecified;
        
        private decimal gI_QTYField;
        
        private bool gI_QTYFieldSpecified;
        
        private string dELIVERY_STATUSField;
        
        private string rEJECT_REASONField;
        
        private string rEJECT_DESCField;
        
        private string iTEM_NOTEField;
        
        private System.DateTime pO_DAT_SField;
        
        private bool pO_DAT_SFieldSpecified;
        
        private string pOITM_NO_SField;
        
        private string iTEM_CATEGField;
        
        private string dUE_PROMISE_TIMEField;
        
        private string pROD_PLANNING_STATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DOC_NUMBER
        {
            get
            {
                return this.dOC_NUMBERField;
            }
            set
            {
                this.dOC_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ITM_NUMBER
        {
            get
            {
                return this.iTM_NUMBERField;
            }
            set
            {
                this.iTM_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MATERIAL
        {
            get
            {
                return this.mATERIALField;
            }
            set
            {
                this.mATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CUST_MAT35
        {
            get
            {
                return this.cUST_MAT35Field;
            }
            set
            {
                this.cUST_MAT35Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SHORT_TEXT
        {
            get
            {
                return this.sHORT_TEXTField;
            }
            set
            {
                this.sHORT_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string PLANT
        {
            get
            {
                return this.pLANTField;
            }
            set
            {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string BATCH
        {
            get
            {
                return this.bATCHField;
            }
            set
            {
                this.bATCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SALES_UNIT
        {
            get
            {
                return this.sALES_UNITField;
            }
            set
            {
                this.sALES_UNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string VMI_MATTYPE
        {
            get
            {
                return this.vMI_MATTYPEField;
            }
            set
            {
                this.vMI_MATTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string VMI_RRNO
        {
            get
            {
                return this.vMI_RRNOField;
            }
            set
            {
                this.vMI_RRNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string HG_LV_ITEM
        {
            get
            {
                return this.hG_LV_ITEMField;
            }
            set
            {
                this.hG_LV_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal UNIT_PRICE
        {
            get
            {
                return this.uNIT_PRICEField;
            }
            set
            {
                this.uNIT_PRICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UNIT_PRICESpecified
        {
            get
            {
                return this.uNIT_PRICEFieldSpecified;
            }
            set
            {
                this.uNIT_PRICEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal NET_VALUE
        {
            get
            {
                return this.nET_VALUEField;
            }
            set
            {
                this.nET_VALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NET_VALUESpecified
        {
            get
            {
                return this.nET_VALUEFieldSpecified;
            }
            set
            {
                this.nET_VALUEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal TAX_AMOUNT
        {
            get
            {
                return this.tAX_AMOUNTField;
            }
            set
            {
                this.tAX_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TAX_AMOUNTSpecified
        {
            get
            {
                return this.tAX_AMOUNTFieldSpecified;
            }
            set
            {
                this.tAX_AMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public System.DateTime REQ_DATE
        {
            get
            {
                return this.rEQ_DATEField;
            }
            set
            {
                this.rEQ_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REQ_DATESpecified
        {
            get
            {
                return this.rEQ_DATEFieldSpecified;
            }
            set
            {
                this.rEQ_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal REQ_QTY
        {
            get
            {
                return this.rEQ_QTYField;
            }
            set
            {
                this.rEQ_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REQ_QTYSpecified
        {
            get
            {
                return this.rEQ_QTYFieldSpecified;
            }
            set
            {
                this.rEQ_QTYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal CUM_CF_QTY
        {
            get
            {
                return this.cUM_CF_QTYField;
            }
            set
            {
                this.cUM_CF_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CUM_CF_QTYSpecified
        {
            get
            {
                return this.cUM_CF_QTYFieldSpecified;
            }
            set
            {
                this.cUM_CF_QTYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public decimal DELIVERY_QTY
        {
            get
            {
                return this.dELIVERY_QTYField;
            }
            set
            {
                this.dELIVERY_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DELIVERY_QTYSpecified
        {
            get
            {
                return this.dELIVERY_QTYFieldSpecified;
            }
            set
            {
                this.dELIVERY_QTYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public decimal GI_QTY
        {
            get
            {
                return this.gI_QTYField;
            }
            set
            {
                this.gI_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GI_QTYSpecified
        {
            get
            {
                return this.gI_QTYFieldSpecified;
            }
            set
            {
                this.gI_QTYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string DELIVERY_STATUS
        {
            get
            {
                return this.dELIVERY_STATUSField;
            }
            set
            {
                this.dELIVERY_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string REJECT_REASON
        {
            get
            {
                return this.rEJECT_REASONField;
            }
            set
            {
                this.rEJECT_REASONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string REJECT_DESC
        {
            get
            {
                return this.rEJECT_DESCField;
            }
            set
            {
                this.rEJECT_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string ITEM_NOTE
        {
            get
            {
                return this.iTEM_NOTEField;
            }
            set
            {
                this.iTEM_NOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public System.DateTime PO_DAT_S
        {
            get
            {
                return this.pO_DAT_SField;
            }
            set
            {
                this.pO_DAT_SField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PO_DAT_SSpecified
        {
            get
            {
                return this.pO_DAT_SFieldSpecified;
            }
            set
            {
                this.pO_DAT_SFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string POITM_NO_S
        {
            get
            {
                return this.pOITM_NO_SField;
            }
            set
            {
                this.pOITM_NO_SField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string ITEM_CATEG
        {
            get
            {
                return this.iTEM_CATEGField;
            }
            set
            {
                this.iTEM_CATEGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string DUE_PROMISE_TIME
        {
            get
            {
                return this.dUE_PROMISE_TIMEField;
            }
            set
            {
                this.dUE_PROMISE_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string PROD_PLANNING_STATUS
        {
            get
            {
                return this.pROD_PLANNING_STATUSField;
            }
            set
            {
                this.pROD_PLANNING_STATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISODetailInquiryReqItem1
    {
        
        private string dOC_NUMBERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DOC_NUMBER
        {
            get
            {
                return this.dOC_NUMBERField;
            }
            set
            {
                this.dOC_NUMBERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISODetailInquiryReqItem2
    {
        
        private string mATERIALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATERIAL
        {
            get
            {
                return this.mATERIALField;
            }
            set
            {
                this.mATERIALField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISODetailInquiryReqItem3
    {
        
        private string sALES_ORGField;
        
        private string dISTR_CHANField;
        
        private string dIVISIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SALES_ORG
        {
            get
            {
                return this.sALES_ORGField;
            }
            set
            {
                this.sALES_ORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DISTR_CHAN
        {
            get
            {
                return this.dISTR_CHANField;
            }
            set
            {
                this.dISTR_CHANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DIVISION
        {
            get
            {
                return this.dIVISIONField;
            }
            set
            {
                this.dIVISIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:scg.co.th:PAPER:VMI:SO")]
    public partial class DT_VMISODetailInquiryReqItem4
    {
        
        private string pLANTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PLANT
        {
            get
            {
                return this.pLANTField;
            }
            set
            {
                this.pLANTField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_VMISODetailInquiry_OSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:scg.co.th:PAPER:VMI:SO", Order=0)]
        public SI_VMISODetailInquiry_OSService.DT_VMISODetailInquiryReq MT_VMISODetailInquiryReq;
        
        public SI_VMISODetailInquiry_OSRequest()
        {
        }
        
        public SI_VMISODetailInquiry_OSRequest(SI_VMISODetailInquiry_OSService.DT_VMISODetailInquiryReq MT_VMISODetailInquiryReq)
        {
            this.MT_VMISODetailInquiryReq = MT_VMISODetailInquiryReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_VMISODetailInquiry_OSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:scg.co.th:PAPER:VMI:SO", Order=0)]
        public SI_VMISODetailInquiry_OSService.DT_VMISODetailInquiryRes MT_VMISODetailInquiryRes;
        
        public SI_VMISODetailInquiry_OSResponse()
        {
        }
        
        public SI_VMISODetailInquiry_OSResponse(SI_VMISODetailInquiry_OSService.DT_VMISODetailInquiryRes MT_VMISODetailInquiryRes)
        {
            this.MT_VMISODetailInquiryRes = MT_VMISODetailInquiryRes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface SI_VMISODetailInquiry_OSChannel : SI_VMISODetailInquiry_OSService.SI_VMISODetailInquiry_OS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class SI_VMISODetailInquiry_OSClient : System.ServiceModel.ClientBase<SI_VMISODetailInquiry_OSService.SI_VMISODetailInquiry_OS>, SI_VMISODetailInquiry_OSService.SI_VMISODetailInquiry_OS
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SI_VMISODetailInquiry_OSClient(EndpointConfiguration endpointConfiguration) : 
                base(SI_VMISODetailInquiry_OSClient.GetBindingForEndpoint(endpointConfiguration), SI_VMISODetailInquiry_OSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_VMISODetailInquiry_OSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SI_VMISODetailInquiry_OSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_VMISODetailInquiry_OSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SI_VMISODetailInquiry_OSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_VMISODetailInquiry_OSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SI_VMISODetailInquiry_OSService.SI_VMISODetailInquiry_OSResponse> SI_VMISODetailInquiry_OSService.SI_VMISODetailInquiry_OS.SI_VMISODetailInquiry_OSAsync(SI_VMISODetailInquiry_OSService.SI_VMISODetailInquiry_OSRequest request)
        {
            return base.Channel.SI_VMISODetailInquiry_OSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SI_VMISODetailInquiry_OSService.SI_VMISODetailInquiry_OSResponse> SI_VMISODetailInquiry_OSAsync(SI_VMISODetailInquiry_OSService.DT_VMISODetailInquiryReq MT_VMISODetailInquiryReq)
        {
            SI_VMISODetailInquiry_OSService.SI_VMISODetailInquiry_OSRequest inValue = new SI_VMISODetailInquiry_OSService.SI_VMISODetailInquiry_OSRequest();
            inValue.MT_VMISODetailInquiryReq = MT_VMISODetailInquiryReq;
            return ((SI_VMISODetailInquiry_OSService.SI_VMISODetailInquiry_OS)(this)).SI_VMISODetailInquiry_OSAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public new virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port_D))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port_Q))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port_P))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port_D))
            {
                return new System.ServiceModel.EndpointAddress("https://cxdwd.scg.co.th/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
                        "S_PAPER_VMI_D&receiverParty=&receiverService=&interface=SI_VMISODetailInquiry_OS" +
                        "&interfaceNamespace=urn%3Ascg.co.th%3APAPER%3AVMI%3ASO");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port_Q))
            {
                return new System.ServiceModel.EndpointAddress("https://cxqwd.scg.co.th/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
                        "S_PAPER_VMI_Q&receiverParty=&receiverService=&interface=SI_VMISODetailInquiry_OS" +
                        "&interfaceNamespace=urn%3Ascg.co.th%3APAPER%3AVMI%3ASO");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port_P))
            {
                return new System.ServiceModel.EndpointAddress("https://cxpwd.scg.co.th/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
                        "S_PAPER_VMI_P&receiverParty=&receiverService=&interface=SI_VMISODetailInquiry_OS" +
                        "&interfaceNamespace=urn%3Ascg.co.th%3APAPER%3AVMI%3ASO");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port_D,
            
            HTTPS_Port_Q,
            
            HTTPS_Port_P,
        }
    }
}
